Refactoring in ConfigurationManager class (config_manager.py)
ivadomed/ivadomed pull request #1195
Opened 2022-10-01 19:23 UTC by kaidalisohaib

## Checklist

#### GitHub

- [X] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've assigned a reviewer

#### PR contents

- [X] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [X] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

- Added function comments to ALL functions within the class.
- Replaced all single letter variables with more meaningful name within the class.
- Added type hinting to ALL objects/variables within the class.

2022-10-24 00:22 UTC, dyt811 requested changes
Hi, Sohaib. Thanks for the PR. 

Minor changes requested to fix a few non-essential things. 

Could you also update the first few functions used in this class as well and add the missing type/return type hint and replace single value variables.

2022-10-24 00:22 UTC, dyt811 commented on ivadomed/config_manager.py
> +    def __init__(self, path_context: str) -> None:
It is okay to leave `none` out in the return type hint usually.

2022-10-24 00:22 UTC, dyt811 commented on ivadomed/config_manager.py
> +    def change_keys_values(self, config_updated: dict, keys: KeysView) -> None:
Technically, `keys` here would be just a list of strings instead of KyesView.

2022-10-24 00:22 UTC, dyt811 commented on ivadomed/config_manager.py
> +    def _display_differing_keys(self) -> None:
Ditto above.

2022-10-24 00:22 UTC, dyt811 commented on ivadomed/config_manager.py
> +    def _validate_path(self) -> None:
Ditto above.

2022-10-24 00:22 UTC, dyt811 commented on ivadomed/config_manager.py
> +    def config_updated(self, config_updated: dict) -> None:
Ditto above.

2022-10-25 17:36 UTC, kaidalisohaib reviewed
Thanks for the tips.

2022-10-31 17:23 UTC, dyt811 approved these changes
Thanks!

2022-11-14 07:09 UTC, merged