Using keywords for ivadomed/scripts folder
ivadomed/ivadomed pull request #934
Opened 2021-09-02 15:54 UTC by cakester

## Checklist

#### GitHub

- [ ] I've given this PR a concise, self-descriptive, and meaningful title
- [ ] I've linked relevant issues in the PR body
- [ ] I've applied [the relevant labels](https://www.neuro.polymtl.ca/software/contributing#pr_labels) to this PR
- [ ] I've assigned a reviewer

#### PR contents

- [ ] I've consulted [ivadomed's internal developer documentation](https://github.com/ivadomed/ivadomed/wiki) to ensure my contribution is in line with any relevant design decisions
- [ ] I've added [relevant tests](https://github.com/ivadomed/ivadomed/wiki/tests) for my contribution
- [ ] I've updated the [relevant documentation](https://github.com/ivadomed/ivadomed/wiki/documentation) for my changes, including argparse descriptions, docstrings, and ReadTheDocs tutorial pages

## Description

using keywords for ivadomed/scripts folder

## Linked issues

2021-09-06 00:49 UTC, dyt811 requested changes
Please ensure the import statement correction is made. Thanks a lot for the great work.

2021-09-06 00:49 UTC, dyt811 commented on ivadomed/scripts/visualize_transforms.py
> +            print(f"\t{dict(metadata)}")
Could you try to see which `logger info/debug` we can replace the `print` with here? I thought we replaced all print statements.

2021-09-07 16:37 UTC, cakester commented on ivadomed/object_detection/utils.py
> +    bounding_box_path = Path(object_detection_params.get(ObjectDetectionParamsKW.PATH_OUTPUT), 'bounding_boxes.json')
$ grep bounding_boxes.json .
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
./ivadomed/object_detection/utils.py:128:    file_path = Path(path_output, 'bounding_boxes.json')
./ivadomed/object_detection/utils.py:244:    bounding_box_path = Path(object_detection_params.get(ObjectDetectionParamsKW.PATH_OUTPUT), 'bounding_boxes.json')
./testing/unit_tests/test_bounding_box.py:82:    bounding_box_path = os.path.join(PATH_OUTPUT, 'bounding_boxes.json')

just used 3 times

2021-09-07 16:48 UTC, cakester commented on ivadomed/scripts/automate_training.py
>      split_path = "./" + "common_split_datasets.joblib"
$ grep \'train\' .
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
./dev/class_balance.py:57:    for ds_lst, ds_name in zip([train_lst, valid_lst, test_lst], ['train', 'valid', 'test']):
./dev/metadata_config.py:24:    for subset in ['train', 'validation', 'test']:
./dev/plot_cluster_metadata.py:39:    for s, y_val in zip(['train', 'valid', 'test'], [0.25, 0.5, 0.75]):
./dev/plot_cluster_metadata.py:63:    for subset in ['train', 'valid', 'test']:
./dev/plot_cluster_metadata.py:85:        values = [v for s in ['train', 'valid', 'test'] for v in metadata_dct[s][m]]
./ivadomed/loader/utils.py:178:    split_dct = {'train': train_lst, 'valid': valid_lst, 'test': test_lst}
./ivadomed/loader/utils.py:200:        train_lst, valid_lst, test_lst = old_split['train'], old_split['valid'], old_split['test']
./ivadomed/main.py:36:    command_group.add_argument("--train", dest='train', action='store_true',
./ivadomed/main.py:385:    if command == 'train':
./ivadomed/main.py:423:        if command != 'train':  # If command == train, then ds_valid already load
./ivadomed/main.py:450:    if command == 'train':
./ivadomed/scripts/automate_training.py:180:    split_dct = {'train': train_lst, 'valid': valid_lst, 'test': test_lst}

2021-09-09 12:48 UTC, dyt811 approved these changes
All good thanks a lot. We should keep an eye out for future simple text "train" "test" as they pop up in various contexts and would benefit more from context specific keywords conversion. We can leave them as it is for now. Might need a future PR/issues to specifically review that.

2021-09-09 14:35 UTC, merged